#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gom
Version  : 0.3.3
Release  : 1
URL      : https://download.gnome.org/sources/gom/0.3/gom-0.3.3.tar.xz
Source0  : https://download.gnome.org/sources/gom/0.3/gom-0.3.3.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: gom-data
Requires: gom-lib
Requires: gom-python
BuildRequires : glibc-bin
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pygobject-python
BuildRequires : python3

%description
---------------------------------------------------------------------------
libgom - GObject Data Mapper
---------------------------------------------------------------------------

%package data
Summary: data components for the gom package.
Group: Data

%description data
data components for the gom package.


%package dev
Summary: dev components for the gom package.
Group: Development
Requires: gom-lib
Requires: gom-data
Provides: gom-devel

%description dev
dev components for the gom package.


%package lib
Summary: lib components for the gom package.
Group: Libraries
Requires: gom-data

%description lib
lib components for the gom package.


%package python
Summary: python components for the gom package.
Group: Default

%description python
python components for the gom package.


%prep
%setup -q -n gom-0.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518724399
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain  builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gom-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/gom-1.0/gom/gom-adapter.h
/usr/include/gom-1.0/gom/gom-autocleanups.h
/usr/include/gom-1.0/gom/gom-command-builder.h
/usr/include/gom-1.0/gom/gom-command.h
/usr/include/gom-1.0/gom/gom-cursor.h
/usr/include/gom-1.0/gom/gom-error.h
/usr/include/gom-1.0/gom/gom-filter.h
/usr/include/gom-1.0/gom/gom-repository.h
/usr/include/gom-1.0/gom/gom-resource-group.h
/usr/include/gom-1.0/gom/gom-resource.h
/usr/include/gom-1.0/gom/gom-sorting.h
/usr/include/gom-1.0/gom/gom.h
/usr/lib64/libgom-1.0.so
/usr/lib64/pkgconfig/gom-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgom-1.0.so.0
/usr/lib64/libgom-1.0.so.0.1.0

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*
